spring:
  datasource:
    username: root
    password: shenwei123456
    url: jdbc:mysql://localhost:3306/nettyim_demo?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useSSL=false
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    com.example.nettyim_demo.mapper: debug

mybatis-plus:
  global-config:
    db-config:
      id-type: auto
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
