package com.example.nettyim_demo.netty.message;

public interface MessageType {
    int REGISTER_REQUEST_MESSAGE = 0;
    int REGISTER_RESPONSE_MESSAGE = 1;
    int LOGIN_REQUEST_MESSAGE = 2;
    int LOGIN_RESPONSE_MESSAGE = 3;
    int LOGOUT_REQUEST_MESSAGE = 4;
    int LOGOUT_RESPONSE_MESSAGE = 5;
    int CHAT_REQUEST_MESSAGE = 6;
    int CHAT_RESPONSE_MESSAGE = 7;
    int GROUP_CHAT_REQUEST_MESSAGE = 8;
    int GROUP_CHAT_RESPONSE_MESSAGE = 9;
    int GROUP_CREATE_REQUEST_MESSAGE = 10;
    int GROUP_CREATE_RESPONSE_MESSAGE = 11;
    int GROUP_JOIN_REQUEST_MESSAGE = 12;
    int GROUP_JOIN_RESPONSE_MESSAGE = 13;
    int GROUP_LEAVE_REQUEST_MESSAGE = 14;
    int GROUP_LEAVE_RESPONSE_MESSAGE = 15;
    int GROUP_MEMBER_LIST_REQUEST_MESSAGE = 16;
    int GROUP_MEMBER_LIST_RESPONSE_MESSAGE = 17;
    int GROUP_LIST_REQUEST_MESSAGE = 18;
    int GROUP_LIST_RESPONSE_MESSAGE = 19;
    int GROUP_ALL_REQUEST_MESSAGE = 20;
    int GROUP_ALL_RESPONSE_MESSAGE = 21;
    int PING_MESSAGE = 100;
}
