package com.example.nettyim_demo.netty.message;

public interface MessageType {
    int LOGIN_REQUEST_MESSAGE = 0;
    int LOGIN_RESPONSE_MESSAGE = 1;
    int LOGOUT_REQUEST_MESSAGE = 2;
    int LOGOUT_RESPONSE_MESSAGE = 3;
    int CHAT_REQUEST_MESSAGE = 4;
    int CHAT_RESPONSE_MESSAGE = 5;
    int GROUP_CHAT_REQUEST_MESSAGE = 6;
    int GROUP_CHAT_RESPONSE_MESSAGE = 7;
    int GROUP_CREATE_REQUEST_MESSAGE = 8;
    int GROUP_CREATE_RESPONSE_MESSAGE = 9;
    int GROUP_JOIN_REQUEST_MESSAGE = 10;
    int GROUP_JOIN_RESPONSE_MESSAGE = 11;
    int GROUP_LEAVE_REQUEST_MESSAGE = 12;
    int GROUP_LEAVE_RESPONSE_MESSAGE = 13;
    int GROUP_MEMBER_LIST_REQUEST_MESSAGE = 14;
    int GROUP_MEMBER_LIST_RESPONSE_MESSAGE = 15;
    int HEARTBEAT_REQUEST_MESSAGE = 16;
    int HEARTBEAT_RESPONSE_MESSAGE = 17;
}
